description: 05 - convnext nano

data:
  dataset: data.datasets.EndoVis17

training:
  epochs: 50

  optimizer:
    name: torch.optim.AdamW
    params:
      lr: 8.0e-4
      weight_decay: 1.0e-4
    encoder_lr_mod: 0.5

  scheduler:
    name: schedulers.custom.WarmupCosineAnnealingLR
    params:
      warmup_epochs: 1
      total_epochs: 50
      steps_per_epoch: 169
      start_factor: 0.1
      eta_min: 8.0e-6 # lr / 100

  encoder:
    name: models.encoders.timm.Encoder
    params:
      model_name: convnextv2_nano # atto, femto, pico, nano, tiny, base, large, huge
      pretrained: true

  tasks:
    segmentation:
      enabled: true
      distillation:
        enabled: true
    disparity:
      enabled: true
      distillation:
        enabled: true
        criterion:
          name: criterions.disparity.PixelWiseKLDivLoss
          params:
            temperature_start: 1.0
            temperature_end: 4.0
            total_epochs: 50
            steps_per_epoch: 169

  weighting:
    inter:
      name: criterions.weighting.DynamicTaskPriority
      params:
        alpha: 0.2 # Faster reaction
        gamma: 0.3 # Punish winning task more
        metric_key_segmentation: 'performance/validation/segmentation/DICE_score/instrument_mean'
        metric_is_score_segmentation: true
        metric_key_disparity: 'performance/validation/disparity/AbsRel_rate'
        metric_is_score_disparity: false
    intra_segmentation:
      name: criterions.weighting.CompetenceDecay
      params:
        alpha: 0.1 # Abandon teacher faster
        teacher_performance: 0.9604
        inverse: false
        metric_key: 'performance/validation/misc/interceptDICE_score'
        metric_is_score: true
    intra_disparity:
      name: criterions.weighting.CompetenceDecay
      params:
        alpha: 0.1 # Abandon teacher faster
        teacher_performance: 0.0809
        inverse: false
        metric_key: 'performance/validation/misc/interceptAbsRel_rate'
        metric_is_score: false
