description: 01 - Highly increased epochs with MultiStepLR and normalized losses

data:
  dataset: data.datasets.EndoVis17

training:
  epochs: 200

  optimizer:
    name: torch.optim.AdamW
    params:
      lr: 1.0e-4
      weight_decay: 1.0e-4
    encoder_lr_mod: 1.0

  scheduler:
    name: schedulers.custom.WarmupMultiStepLR
    params:
      warmup_epochs: 10
      milestones: [160, 180]
      gamma: 0.1
      steps_per_epoch: 169
      start_factor: 0.01

  encoder:
    name: models.encoders.timm.Encoder
    params:
      model_name: convnextv2_tiny # atto, femto, pico, nano, tiny, base, large, huge
      pretrained: true

  tasks:
    segmentation:
      enabled: false
      distillation:
        enabled: false
    disparity:
      enabled: true
      distillation:
        enabled: false
