description: Debugging Multi Task Segmentation and Disparity with Knowledge Distillation

data:
  dataset: data.datasets.EndoVis17
  max_disparity: 512

training:
  epochs: 150

  optimizer:
    name: torch.optim.AdamW
    params:
      lr: 1.42e-4
    encoder_lr_mod: 1

  scheduler:
    name: schedulers.custom.WarmupCosineAnnealingLR
    params:
      warmup_epochs: 1
      total_epochs: 150
      steps_per_epoch: 675
      start_factor: 0.01
      eta_min: 5.5e-8

  encoder:
    name: models.encoders.timm.Encoder
    params:
      model_name: convnextv2_tiny # atto, femto, pico, nano, tiny, base, large, huge
      pretrained: true

  tasks:
    segmentation:
      enabled: true
      distillation:
        enabled: false
    disparity:
      enabled: true
      distillation:
        enabled: false

  weighting:
    inter:
      name: criterions.weighting.Unweighted
      params: {}
