description: 02 - Increased LR, temperature decay for disp, decreased disp alpha, increased seg alpha

data:
  dataset: data.datasets.EndoVis17

training:
  epochs: 25

  optimizer:
    name: torch.optim.AdamW
    params:
      lr: 8.0e-4
      weight_decay: 1.0e-4
    encoder_lr_mod: 0.5

  scheduler:
    name: schedulers.custom.WarmupCosineAnnealingLR
    params:
      warmup_epochs: 1
      total_epochs: 50
      steps_per_epoch: 169
      start_factor: 0.1
      eta_min: 8.0e-6 # lr / 100

  encoder:
    name: models.encoders.timm.Encoder
    params:
      model_name: convnextv2_tiny # atto, femto, pico, nano, tiny, base, large, huge
      pretrained: true

  tasks:
    segmentation:
      enabled: true
      distillation:
        enabled: false
    disparity:
      enabled: false
      distillation:
        enabled: false
