description: Experiment 01 - Baseline / Dynamic Loss Weighting

training:
  tasks:
    segmentation:
      enabled: true
      distillation:
        enabled: true
    disparity:
      enabled: true
      distillation:
        enabled: true