description: Experiment 07 - Fixed Task Weighting

training:
  tasks:
    segmentation:
      enabled: true
      distillation:
        enabled: true
    disparity:
      enabled: true
      distillation:
        enabled: true

  weighting:
    inter:
      name: criterions.weighting.Unweighted
      params: {}