description: Finetune the SegFormer segmentation teacher on EndoVis17 in a notebook.

data:
  dataset: data.datasets.EndoVis17

  num_of_classes:
    segmentation: 8

training:
  epochs: 50
  validation: true

  batch_size:  1
  accumulate_grad_batches: 8

  optimizer:
    name: torch.optim.AdamW
    params:
      lr: 6.0e-5

  scheduler:
    name: schedulers.custom.WarmupCosineAnnealingLR
    params:
      warmup_epochs: 1
      total_epochs: 50
      steps_per_epoch: 169
      start_factor: 0.5
      eta_min: 6.0e-8 # lr / 1000

  tasks:
    segmentation:
      enabled: true
  
