description: Debugging Multi Task Segmentation and Disparity with Knowledge Distillation

data:
  dataset: data.datasets.EndoVis17
  max_disparity: 512

training:
  epochs: 250

  optimizer:
    name: torch.optim.AdamW
    params:
      lr: 5.0e-4
    encoder_lr_mod: 1.0

  scheduler:
    name: torch.optim.lr_scheduler.LinearLR
    params:
      start_factor: 0.5
      total_iters: 675

  tasks:
    segmentation:
      enabled: true
      knowledge_distillation:
        enabled: false
    disparity:
      enabled: false
      knowledge_distillation:
        enabled: false

logging:
  n_validation_images: 0