description: DISP Baseline

data:
  dataset: data.datasets.EndoVis17

training:
  epochs: 200

  optimizer:
    name: torch.optim.AdamW
    params:
      lr: 1.0e-4
    encoder_lr_mod: 1.0

  scheduler:
    name: schedulers.custom.WarmupCosineAnnealingLR
    params:
      warmup_epochs: 1
      total_epochs: 200
      steps_per_epoch: 169
      start_factor: 0.5
      eta_min: 1.0e-7 # lr / 1000

  tasks:
    segmentation:
      enabled: false
      distillation:
        enabled: false
    disparity:
      enabled: true
      distillation:
        enabled: false
