description: SEG Baseline with Resnet

data:
  dataset: data.datasets.EndoVis17

training:
  epochs: 15

  optimizer:
    name: torch.optim.AdamW
    params:
      lr: 1.0e-3
    encoder_lr_mod: 1.0

  scheduler:
    name: schedulers.custom.WarmupCosineAnnealingLR
    params:
      warmup_epochs: 1
      total_epochs: 15
      steps_per_epoch: 169
      start_factor: 0.5
      eta_min: 1.0e-6 # lr / 1000

  encoder:
    name: models.encoders.timm.Encoder
    params:
      model_name: resnet50
      pretrained: true

  tasks:
    segmentation:
      enabled: true
      distillation:
        enabled: false
    disparity:
      enabled: false
      distillation:
        enabled: false
